version: '2'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:latest
    hostname: 'sqlserver'
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd#1
      MSSQL_PID: Developer
    ports:
      - '1433:1433'
    volumes:
      - /srv/docker-data/sqldata:/var/opt/mssql
